name: gh-pages CI

on:
  push:
    branches: [ main ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Branch Merge
      uses: everlytic/branch-merge@1.1.2
      with:
        source_ref: main
        target_branch: gh-pages

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Setup Node.js environment 
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'
    - run: npm ci
    - run: npm run app:build

  update:
    runs-on: ubuntu-latest
    steps:
    - name: Update static files
      run: |
        git config user.name "Dev-Blog Bot"
        git config user.email "bot@dev-blog.com"
        git add .
        git commit -m "[Bot] Update static files"
        git push
